[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm ci --legacy-peer-deps"]
cacheDirectories = ["/root/.npm"]
paths = ["/app/node_modules/.bin"]

[phases.build]
cmds = ["npm run build"]
cacheDirectories = ["node_modules/.cache"]

[start]
cmd = "npx serve -s build -l 3000"
